when:
  - event: push
    branch: mcp-server

depends_on:
  - create-release

labels:
  platform: linux/amd64

steps:
  - name: build-and-package
    image: debian:12
    commands:
      - apt-get update
      - >-
        apt-get install -y --no-install-recommends
        autoconf
        automake
        build-essential
        ca-certificates
        byacc
        dos2unix
        flex
        git
        libasound2-dev
        libcap-dev
        libcurl4-openssl-dev
        libevdev-dev
        libflac-dev
        libgif-dev
        libglew-dev
        libgtk-3-dev
        libieee1284-3-dev
        libmicrohttpd-dev
        libmp3lame-dev
        libmpg123-dev
        libpcap-dev
        libpng-dev
        libpulse-dev
        libusb-1.0-0-dev
        libvorbis-dev
        pkg-config
        portaudio19-dev
        xa65
        zip
      - cd vice
      - find . -name config.status -exec rm -f {} +
      - rm -rf build-gui build-headless
      - test -f Makefile && make distclean || true
      - ./src/buildtools/genvicedate_h.sh
      - ./autogen.sh
      - cd ..
      - git fetch --tags
      - VERSION=$$(bash scripts/compute-version.sh --current)
      - cd vice
      # --- GUI build ---
      - mkdir -p build-gui && cd build-gui
      - >-
        ../configure
        --enable-option-checking=fatal
        --enable-gtk3ui
        --enable-mcp-server
        --enable-cpuhistory
        --enable-ethernet
        --enable-midi
        --enable-parsid
        --enable-catweasel
        --disable-arch
        --disable-pdf-docs
        --disable-html-docs
        --with-alsa
        --with-fastsid
        --with-flac
        --with-gif
        --with-lame
        --with-libcurl
        --with-libieee1284
        --with-mpg123
        --with-png
        --with-portaudio
        --with-pulse
        --with-resid
        --with-vorbis
      - make -j$$(nproc) -s
      - make DESTDIR=$${PWD}/install-tree install-strip
      - cd install-tree
      - zip -r "../../../$${VERSION}-linux-x86_64-gui.zip" .
      - cd ../../..
      - sha256sum "$${VERSION}-linux-x86_64-gui.zip" > "$${VERSION}-linux-x86_64-gui.zip.sha256"
      - cd vice
      # --- Headless build ---
      - mkdir -p build-headless && cd build-headless
      - >-
        ../configure
        --enable-option-checking=fatal
        --enable-headlessui
        --enable-mcp-server
        --enable-cpuhistory
        --enable-ethernet
        --enable-midi
        --enable-parsid
        --enable-catweasel
        --disable-arch
        --disable-pdf-docs
        --disable-html-docs
        --with-alsa
        --with-fastsid
        --with-flac
        --with-gif
        --with-lame
        --with-libcurl
        --with-libieee1284
        --with-mpg123
        --with-png
        --with-portaudio
        --with-pulse
        --with-resid
        --with-vorbis
      - make -j$$(nproc) -s
      - make DESTDIR=$${PWD}/install-tree install-strip
      - cd install-tree
      - zip -r "../../../$${VERSION}-linux-x86_64-headless.zip" .
      - cd ../../..
      - sha256sum "$${VERSION}-linux-x86_64-headless.zip" > "$${VERSION}-linux-x86_64-headless.zip.sha256"
      - ls -lh $${VERSION}-linux-x86_64-*.zip*

  - name: upload
    image: alpine:3.19
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache bash ca-certificates git github-cli
      - git fetch --tags
      - VERSION=$$(bash scripts/compute-version.sh --current)
      - |
        for f in $${VERSION}-linux-x86_64-*.zip $${VERSION}-linux-x86_64-*.sha256; do
          gh release upload "$${VERSION}" "$${f}" --repo "$${CI_REPO}" --clobber
        done
