when:
  - event: push
    branch: mcp-server

depends_on:
  - create-release

labels:
  platform: linux/amd64

steps:
  - name: build-and-package
    image: fedora:41
    backend_options:
      kubernetes:
        node_selector:
          ci-role: windows
    commands:
      # Install cross-compiler toolchain and dependencies
      - >-
        dnf install -y --setopt=install_weak_deps=False
        gcc gcc-c++ autoconf automake make pkg-config xa
        flex bison dos2unix git zip curl ca-certificates
        mingw64-gcc mingw64-gcc-c++
        mingw64-curl mingw64-flac mingw64-portaudio
        mingw64-giflib mingw64-libvorbis mingw64-libpng
      # Cross-compile libmicrohttpd (no Fedora mingw64 package available)
      - bash scripts/build-windows-cross.sh build-libmicrohttpd
      # Cross-compile VICE headless
      - bash scripts/build-windows-cross.sh build
      # Package into zip with DLLs and data files
      - bash scripts/build-windows-cross.sh package

  - name: upload
    image: fedora:41
    backend_options:
      kubernetes:
        node_selector:
          ci-role: windows
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - dnf install -y --setopt=install_weak_deps=False git gh bash
      - bash scripts/build-windows-cross.sh upload
