when:
  - event: push
    branch: mcp-server

depends_on:
  - create-release

labels:
  platform: darwin/arm64

steps:
  - name: install-deps
    image: bash
    commands:
      - brew update
      - >-
        brew install
        autoconf
        automake
        pkg-config
        xa
        dos2unix
        gtk+3
        librsvg
        adwaita-icon-theme
        glew
        libmicrohttpd
        giflib
        libpng
        libvorbis
        flac
        lame
        mpg123
        libpcap
        libusb
        portaudio

  - name: build-gui
    image: bash
    commands:
      - cd vice
      - rm -rf build-gui build-headless
      - rm -f src/config.h
      - find . -name config.status -exec rm -f {} +
      - ./src/buildtools/genvicedate_h.sh
      - ./autogen.sh
      - mkdir -p build-gui && cd build-gui
      - >-
        ../configure
        --enable-option-checking=fatal
        --enable-gtk3ui
        --enable-mcp-server
        --enable-cpuhistory
        --enable-ethernet
        --enable-midi
        --enable-parsid
        --disable-arch
        --disable-pdf-docs
        --disable-html-docs
        --disable-openmp
        --with-fastsid
        --with-flac
        --with-gif
        --with-lame
        --with-libcurl
        --with-mpg123
        --with-png
        --with-portaudio
        --with-resid
        --with-vorbis
      - make -j$$(sysctl -n hw.ncpu) -s
      - DEPS_PREFIX=$$(brew --prefix) make bindistzip
      - cd ../..
      - git fetch --tags
      - VERSION=$$(bash scripts/compute-version.sh --current)
      - |
        cd vice/build-gui
        DMG_FILE=$$(ls *.dmg 2>/dev/null | head -1 || true)
        ZIP_FILE=$$(ls *.zip 2>/dev/null | head -1 || true)
        if [ -n "$${DMG_FILE}" ]; then
          cp "$${DMG_FILE}" "../../$${VERSION}-macos-arm64-gui.dmg"
          cd ../..
          shasum -a 256 "$${VERSION}-macos-arm64-gui.dmg" > "$${VERSION}-macos-arm64-gui.dmg.sha256"
        elif [ -n "$${ZIP_FILE}" ]; then
          cp "$${ZIP_FILE}" "../../$${VERSION}-macos-arm64-gui.zip"
          cd ../..
          shasum -a 256 "$${VERSION}-macos-arm64-gui.zip" > "$${VERSION}-macos-arm64-gui.zip.sha256"
        else
          echo "ERROR: No package artifact found" && exit 1
        fi

  - name: build-headless
    image: bash
    commands:
      - cd vice
      - rm -rf build-headless
      - mkdir -p build-headless && cd build-headless
      - >-
        ../configure
        --enable-option-checking=fatal
        --enable-headlessui
        --enable-mcp-server
        --enable-cpuhistory
        --enable-ethernet
        --enable-midi
        --enable-parsid
        --disable-arch
        --disable-pdf-docs
        --disable-html-docs
        --disable-openmp
        --with-fastsid
        --with-flac
        --with-gif
        --with-lame
        --with-libcurl
        --with-mpg123
        --with-png
        --with-portaudio
        --with-resid
        --with-vorbis
      - make -j$$(sysctl -n hw.ncpu) -s
      - make DESTDIR=$${PWD}/install-tree install-strip
      - cd ../..
      - git fetch --tags
      - VERSION=$$(bash scripts/compute-version.sh --current)
      - cd vice/build-headless/install-tree
      - zip -r "../../../$${VERSION}-macos-arm64-headless.zip" .
      - cd ../../..
      - shasum -a 256 "$${VERSION}-macos-arm64-headless.zip" > "$${VERSION}-macos-arm64-headless.zip.sha256"

  - name: upload
    image: bash
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - git fetch --tags
      - VERSION=$$(bash scripts/compute-version.sh --current)
      - |
        for f in $${VERSION}-macos-arm64-*; do
          [ -f "$${f}" ] && gh release upload "$${VERSION}" "$${f}" --repo "$${CI_REPO}" --clobber
        done
