when:
  - event: push
    branch: mcp-server

labels:
  platform: linux/amd64

steps:
  - name: create-draft-release
    image: alpine:3.19
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache bash ca-certificates git github-cli
      - git fetch --tags
      - VERSION=$$(bash scripts/compute-version.sh)
      - echo "Creating draft release $${VERSION}"
      # Generate release notes from commit messages since last tag
      - |
        PREV_TAG=$$(git tag -l 'vice-mcp-*' --sort=-v:refname | head -1 || true)
        if [ -n "$${PREV_TAG}" ]; then
          NOTES=$$(git log "$${PREV_TAG}..HEAD" --pretty=format:"- %s" --no-merges)
        else
          NOTES=$$(git log --pretty=format:"- %s" --no-merges -20)
        fi
        if [ -z "$${NOTES}" ]; then
          NOTES="No changes since last release."
        fi
      - |
        if gh release view "$${VERSION}" --repo "$${CI_REPO}" >/dev/null 2>&1; then
          echo "Release $${VERSION} already exists, skipping creation"
        else
          gh release create "$${VERSION}" \
            --repo "$${CI_REPO}" \
            --target "$${CI_COMMIT_SHA}" \
            --title "$${VERSION}" \
            --notes "$${NOTES}" \
            --draft
        fi
