when:
  - event: push
    branch: mcp-server

labels:
  platform: linux/amd64

steps:
  - name: create-draft-release
    image: alpine:3.19
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache bash ca-certificates git github-cli
      - git fetch --tags
      - VERSION=$$(bash scripts/compute-version.sh)
      - echo "Creating draft release $${VERSION}"
      - |
        if gh release view "$${VERSION}" --repo "$${CI_REPO}" >/dev/null 2>&1; then
          echo "Release $${VERSION} already exists, skipping creation"
        else
          gh release create "$${VERSION}" \
            --repo "$${CI_REPO}" \
            --target "$${CI_COMMIT_SHA}" \
            --title "$${VERSION}" \
            --notes "Automated MCP server build from mcp-server branch. Includes GUI and headless variants." \
            --draft \
            --prerelease
        fi
